version: '3'
services:
  ml-server:
    # docker build -t asdr-flask .
    build: .
    env_file:
      - .env
    # ports:
    #   - "5000:5000"
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ml-server
# ```

# ### nginx.conf

# ```nginx
# server {
#     listen 80;
#     server_name localhost;

#     location / {
#         proxy_pass http://flask:5000;
#     }
# }
# ```


    