_backend_args = None
_multiscale_resize_transforms = [
    dict(
        transforms=[
            dict(scale=(
                1280,
                1280,
            ), type='YOLOv5KeepRatioResize'),
            dict(
                allow_scale_up=False,
                pad_val=dict(img=114),
                scale=(
                    1280,
                    1280,
                ),
                type='LetterResize'),
        ],
        type='Compose'),
    dict(
        transforms=[
            dict(scale=(
                1024,
                1024,
            ), type='YOLOv5KeepRatioResize'),
            dict(
                allow_scale_up=False,
                pad_val=dict(img=114),
                scale=(
                    1024,
                    1024,
                ),
                type='LetterResize'),
        ],
        type='Compose'),
    dict(
        transforms=[
            dict(scale=(
                1536,
                1536,
            ), type='YOLOv5KeepRatioResize'),
            dict(
                allow_scale_up=False,
                pad_val=dict(img=114),
                scale=(
                    1536,
                    1536,
                ),
                type='LetterResize'),
        ],
        type='Compose'),
]
affine_scale = 0.5
albu_train_transforms = [
    dict(p=0.01, type='Blur'),
    dict(p=0.01, type='MedianBlur'),
    dict(p=0.01, type='ToGray'),
    dict(p=0.01, type='CLAHE'),
]
anchors = [
    [
        (
            6,
            5,
        ),
        (
            5,
            8,
        ),
        (
            8,
            12,
        ),
    ],
    [
        (
            12,
            8,
        ),
        (
            16,
            10,
        ),
        (
            10,
            16,
        ),
    ],
    [
        (
            7,
            29,
        ),
        (
            28,
            12,
        ),
        (
            16,
            26,
        ),
    ],
    [
        (
            32,
            31,
        ),
        (
            39,
            41,
        ),
        (
            67,
            65,
        ),
    ],
]
backend_args = None
base_lr = 0.01
batch_shapes_cfg = dict(
    batch_size=1,
    extra_pad_ratio=0.5,
    img_size=1280,
    size_divisor=64,
    type='BatchShapePolicy')
class_name = (
    '11522_tx_dyn1',
    '11522_tx_ynyn0d1',
    '115_1way_ds_w_motor',
    '115_3ways_ds_w_motor',
    '115_breaker',
    '115_buffer',
    '115_cvt_1p',
    '115_cvt_3p',
    '115_ds',
    '115_gs',
    '115_gs_w_motor',
    '115_la',
    '115_vt_1p',
    '115_vt_3p',
    '22_breaker',
    '22_cap_bank',
    '22_ds',
    '22_ds_la_out',
    '22_gs',
    '22_ll',
    '22_vt_3p',
    'BCU',
    'DIM',
    'DPM',
    'LL',
    'MU',
    'NGR_future',
    'Q',
    'remote_io_module',
    'ss_man_mode',
    'tele_protection',
    'terminator_double',
    'terminator_single',
    'terminator_splicing_kits',
    'terminator_w_future',
    'v_m',
    'v_m_digital',
)
custom_hooks = [
    dict(
        ema_type='ExpMomentumEMA',
        momentum=0.0001,
        priority=49,
        strict_load=False,
        type='EMAHook',
        update_buffers=True),
]
data_root = 'data/asdr6-3-1000oa-split8020/'
dataset_type = 'YOLOv5CocoDataset'
deepen_factor = 0.33
default_hooks = dict(
    checkpoint=dict(
        interval=25,
        max_keep_ckpts=100,
        save_best='auto',
        type='CheckpointHook'),
    logger=dict(interval=5, type='LoggerHook'),
    param_scheduler=dict(
        lr_factor=0.01,
        max_epochs=300,
        scheduler_type='linear',
        type='YOLOv5ParamSchedulerHook',
        warmup_mim_iter=1000),
    sampler_seed=dict(type='DistSamplerSeedHook'),
    timer=dict(type='IterTimerHook'),
    visualization=dict(type='mmdet.DetVisualizationHook'))
default_scope = 'mmyolo'
env_cfg = dict(
    cudnn_benchmark=True,
    dist_cfg=dict(backend='nccl'),
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0))
img_scale = (
    1280,
    1280,
)
img_scales = [
    (
        640,
        640,
    ),
    (
        320,
        320,
    ),
    (
        960,
        960,
    ),
]
isTest = True
load_from = 'https://download.openmmlab.com/mmyolo/v0/yolov5/yolov5_s-p6-v62_syncbn_fast_8xb16-300e_coco/yolov5_s-p6-v62_syncbn_fast_8xb16-300e_coco_20221027_215044-58865c19.pth'
log_level = 'INFO'
log_processor = dict(by_epoch=True, type='LogProcessor', window_size=50)
loss_bbox_weight = 0.05
loss_cls_weight = 0.5
loss_obj_weight = 1.0
lr_factor = 0.01
max_epochs = 300
max_keep_ckpts = 3
metainfo = dict(
    classes=(
        '11522_tx_dyn1',
        '11522_tx_ynyn0d1',
        '115_1way_ds_w_motor',
        '115_3ways_ds_w_motor',
        '115_breaker',
        '115_buffer',
        '115_cvt_1p',
        '115_cvt_3p',
        '115_ds',
        '115_gs',
        '115_gs_w_motor',
        '115_la',
        '115_vt_1p',
        '115_vt_3p',
        '22_breaker',
        '22_cap_bank',
        '22_ds',
        '22_ds_la_out',
        '22_gs',
        '22_ll',
        '22_vt_3p',
        'BCU',
        'DIM',
        'DPM',
        'LL',
        'MU',
        'NGR_future',
        'Q',
        'remote_io_module',
        'ss_man_mode',
        'tele_protection',
        'terminator_double',
        'terminator_single',
        'terminator_splicing_kits',
        'terminator_w_future',
        'v_m',
        'v_m_digital',
    ),
    palette=[
        (
            0,
            0,
            0,
        ),
        (
            66,
            0,
            75,
        ),
        (
            120,
            0,
            137,
        ),
        (
            130,
            0,
            147,
        ),
        (
            105,
            0,
            156,
        ),
        (
            30,
            0,
            166,
        ),
        (
            0,
            0,
            187,
        ),
        (
            0,
            0,
            215,
        ),
        (
            0,
            52,
            221,
        ),
        (
            0,
            119,
            221,
        ),
        (
            0,
            137,
            221,
        ),
        (
            0,
            154,
            215,
        ),
        (
            0,
            164,
            187,
        ),
        (
            0,
            170,
            162,
        ),
        (
            0,
            170,
            143,
        ),
        (
            0,
            164,
            90,
        ),
        (
            0,
            154,
            15,
        ),
        (
            0,
            168,
            0,
        ),
        (
            0,
            186,
            0,
        ),
        (
            0,
            205,
            0,
        ),
        (
            0,
            224,
            0,
        ),
        (
            0,
            243,
            0,
        ),
        (
            41,
            255,
            0,
        ),
        (
            145,
            255,
            0,
        ),
        (
            203,
            249,
            0,
        ),
        (
            232,
            239,
            0,
        ),
        (
            245,
            222,
            0,
        ),
        (
            255,
            204,
            0,
        ),
        (
            255,
            175,
            0,
        ),
        (
            255,
            136,
            0,
        ),
        (
            255,
            51,
            0,
        ),
        (
            247,
            0,
            0,
        ),
        (
            228,
            0,
            0,
        ),
        (
            215,
            0,
            0,
        ),
        (
            205,
            0,
            0,
        ),
        (
            204,
            90,
            90,
        ),
        (
            204,
            204,
            204,
        ),
    ])
model = dict(
    backbone=dict(
        act_cfg=dict(inplace=True, type='SiLU'),
        arch='P6',
        deepen_factor=0.33,
        norm_cfg=dict(eps=0.001, momentum=0.03, type='BN'),
        out_indices=(
            2,
            3,
            4,
            5,
        ),
        type='YOLOv5CSPDarknet',
        widen_factor=0.5),
    bbox_head=dict(
        head_module=dict(
            featmap_strides=[
                8,
                16,
                32,
                64,
            ],
            in_channels=[
                256,
                512,
                768,
                1024,
            ],
            num_base_priors=3,
            num_classes=37,
            type='YOLOv5HeadModule',
            widen_factor=0.5),
        loss_bbox=dict(
            bbox_format='xywh',
            eps=1e-07,
            iou_mode='ciou',
            loss_weight=0.037500000000000006,
            reduction='mean',
            return_iou=True,
            type='IoULoss'),
        loss_cls=dict(
            loss_weight=0.375,
            reduction='mean',
            type='mmdet.CrossEntropyLoss',
            use_sigmoid=True),
        loss_obj=dict(
            loss_weight=4.0,
            reduction='mean',
            type='mmdet.CrossEntropyLoss',
            use_sigmoid=True),
        obj_level_weights=[
            4.0,
            1.0,
            0.25,
            0.06,
        ],
        prior_generator=dict(
            base_sizes=[
                [
                    (
                        6,
                        5,
                    ),
                    (
                        5,
                        8,
                    ),
                    (
                        8,
                        12,
                    ),
                ],
                [
                    (
                        12,
                        8,
                    ),
                    (
                        16,
                        10,
                    ),
                    (
                        10,
                        16,
                    ),
                ],
                [
                    (
                        7,
                        29,
                    ),
                    (
                        28,
                        12,
                    ),
                    (
                        16,
                        26,
                    ),
                ],
                [
                    (
                        32,
                        31,
                    ),
                    (
                        39,
                        41,
                    ),
                    (
                        67,
                        65,
                    ),
                ],
            ],
            strides=[
                8,
                16,
                32,
                64,
            ],
            type='mmdet.YOLOAnchorGenerator'),
        prior_match_thr=4.0,
        type='YOLOv5Head'),
    data_preprocessor=dict(
        bgr_to_rgb=True,
        mean=[
            0.0,
            0.0,
            0.0,
        ],
        std=[
            255.0,
            255.0,
            255.0,
        ],
        type='YOLOv5DetDataPreprocessor'),
    neck=dict(
        act_cfg=dict(inplace=True, type='SiLU'),
        deepen_factor=0.33,
        in_channels=[
            256,
            512,
            768,
            1024,
        ],
        norm_cfg=dict(eps=0.001, momentum=0.03, type='BN'),
        num_csp_blocks=3,
        out_channels=[
            256,
            512,
            768,
            1024,
        ],
        type='YOLOv5PAFPN',
        widen_factor=0.5),
    test_cfg=dict(
        max_per_img=300,
        multi_label=True,
        nms=dict(iou_threshold=0.65, type='nms'),
        nms_pre=30000,
        score_thr=0.001),
    type='YOLODetector')
model_test_cfg = dict(
    max_per_img=300,
    multi_label=True,
    nms=dict(iou_threshold=0.65, type='nms'),
    nms_pre=30000,
    score_thr=0.001)
norm_cfg = dict(eps=0.001, momentum=0.03, type='BN')
num_classes = 37
num_det_layers = 4
obj_level_weights = [
    4.0,
    1.0,
    0.25,
    0.06,
]
optim_wrapper = dict(
    constructor='YOLOv5OptimizerConstructor',
    optimizer=dict(
        batch_size_per_gpu=16,
        lr=0.01,
        momentum=0.937,
        nesterov=True,
        type='SGD',
        weight_decay=0.0005),
    type='OptimWrapper')
palette = [
    (
        0,
        0,
        0,
    ),
    (
        66,
        0,
        75,
    ),
    (
        120,
        0,
        137,
    ),
    (
        130,
        0,
        147,
    ),
    (
        105,
        0,
        156,
    ),
    (
        30,
        0,
        166,
    ),
    (
        0,
        0,
        187,
    ),
    (
        0,
        0,
        215,
    ),
    (
        0,
        52,
        221,
    ),
    (
        0,
        119,
        221,
    ),
    (
        0,
        137,
        221,
    ),
    (
        0,
        154,
        215,
    ),
    (
        0,
        164,
        187,
    ),
    (
        0,
        170,
        162,
    ),
    (
        0,
        170,
        143,
    ),
    (
        0,
        164,
        90,
    ),
    (
        0,
        154,
        15,
    ),
    (
        0,
        168,
        0,
    ),
    (
        0,
        186,
        0,
    ),
    (
        0,
        205,
        0,
    ),
    (
        0,
        224,
        0,
    ),
    (
        0,
        243,
        0,
    ),
    (
        41,
        255,
        0,
    ),
    (
        145,
        255,
        0,
    ),
    (
        203,
        249,
        0,
    ),
    (
        232,
        239,
        0,
    ),
    (
        245,
        222,
        0,
    ),
    (
        255,
        204,
        0,
    ),
    (
        255,
        175,
        0,
    ),
    (
        255,
        136,
        0,
    ),
    (
        255,
        51,
        0,
    ),
    (
        247,
        0,
        0,
    ),
    (
        228,
        0,
        0,
    ),
    (
        215,
        0,
        0,
    ),
    (
        205,
        0,
        0,
    ),
    (
        204,
        90,
        90,
    ),
    (
        204,
        204,
        204,
    ),
]
param_scheduler = None
persistent_workers = True
pre_transform = [
    dict(backend_args=None, type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
]
prior_match_thr = 4.0
resume = False
save_checkpoint_intervals = 10
strides = [
    8,
    16,
    32,
    64,
]
test_cfg = dict(type='TestLoop')
test_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='annotations/val.json',
        batch_shapes_cfg=dict(
            batch_size=1,
            extra_pad_ratio=0.5,
            img_size=1280,
            size_divisor=64,
            type='BatchShapePolicy'),
        data_prefix=dict(img='images/'),
        data_root='data/asdr6-3-1000oa-split8020/',
        metainfo=dict(
            classes=(
                '11522_tx_dyn1',
                '11522_tx_ynyn0d1',
                '115_1way_ds_w_motor',
                '115_3ways_ds_w_motor',
                '115_breaker',
                '115_buffer',
                '115_cvt_1p',
                '115_cvt_3p',
                '115_ds',
                '115_gs',
                '115_gs_w_motor',
                '115_la',
                '115_vt_1p',
                '115_vt_3p',
                '22_breaker',
                '22_cap_bank',
                '22_ds',
                '22_ds_la_out',
                '22_gs',
                '22_ll',
                '22_vt_3p',
                'BCU',
                'DIM',
                'DPM',
                'LL',
                'MU',
                'NGR_future',
                'Q',
                'remote_io_module',
                'ss_man_mode',
                'tele_protection',
                'terminator_double',
                'terminator_single',
                'terminator_splicing_kits',
                'terminator_w_future',
                'v_m',
                'v_m_digital',
            ),
            palette=[
                (
                    0,
                    0,
                    0,
                ),
                (
                    66,
                    0,
                    75,
                ),
                (
                    120,
                    0,
                    137,
                ),
                (
                    130,
                    0,
                    147,
                ),
                (
                    105,
                    0,
                    156,
                ),
                (
                    30,
                    0,
                    166,
                ),
                (
                    0,
                    0,
                    187,
                ),
                (
                    0,
                    0,
                    215,
                ),
                (
                    0,
                    52,
                    221,
                ),
                (
                    0,
                    119,
                    221,
                ),
                (
                    0,
                    137,
                    221,
                ),
                (
                    0,
                    154,
                    215,
                ),
                (
                    0,
                    164,
                    187,
                ),
                (
                    0,
                    170,
                    162,
                ),
                (
                    0,
                    170,
                    143,
                ),
                (
                    0,
                    164,
                    90,
                ),
                (
                    0,
                    154,
                    15,
                ),
                (
                    0,
                    168,
                    0,
                ),
                (
                    0,
                    186,
                    0,
                ),
                (
                    0,
                    205,
                    0,
                ),
                (
                    0,
                    224,
                    0,
                ),
                (
                    0,
                    243,
                    0,
                ),
                (
                    41,
                    255,
                    0,
                ),
                (
                    145,
                    255,
                    0,
                ),
                (
                    203,
                    249,
                    0,
                ),
                (
                    232,
                    239,
                    0,
                ),
                (
                    245,
                    222,
                    0,
                ),
                (
                    255,
                    204,
                    0,
                ),
                (
                    255,
                    175,
                    0,
                ),
                (
                    255,
                    136,
                    0,
                ),
                (
                    255,
                    51,
                    0,
                ),
                (
                    247,
                    0,
                    0,
                ),
                (
                    228,
                    0,
                    0,
                ),
                (
                    215,
                    0,
                    0,
                ),
                (
                    205,
                    0,
                    0,
                ),
                (
                    204,
                    90,
                    90,
                ),
                (
                    204,
                    204,
                    204,
                ),
            ]),
        pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(scale=(
                1280,
                1280,
            ), type='YOLOv5KeepRatioResize'),
            dict(
                allow_scale_up=False,
                pad_val=dict(img=114),
                scale=(
                    1280,
                    1280,
                ),
                type='LetterResize'),
            dict(type='mmdet.LoadAnnotations', with_bbox=True),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                    'pad_param',
                ),
                type='mmdet.PackDetInputs'),
        ],
        test_mode=True,
        type='YOLOv5CocoDataset'),
    drop_last=False,
    num_workers=2,
    persistent_workers=True,
    pin_memory=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
test_evaluator = dict(
    ann_file='data/asdr6-3-1000oa-split8020/annotations/val.json',
    metric='bbox',
    proposal_nums=(
        100,
        1,
        10,
    ),
    type='mmdet.CocoMetric')
test_pipeline = [
    dict(backend_args=None, type='LoadImageFromFile'),
    dict(scale=(
        1280,
        1280,
    ), type='YOLOv5KeepRatioResize'),
    dict(
        allow_scale_up=False,
        pad_val=dict(img=114),
        scale=(
            1280,
            1280,
        ),
        type='LetterResize'),
    dict(type='mmdet.LoadAnnotations', with_bbox=True),
    dict(
        meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'scale_factor',
            'pad_param',
        ),
        type='mmdet.PackDetInputs'),
]
train_ann_file = 'annotations/train.json'
train_batch_size_per_gpu = 8
train_cfg = dict(max_epochs=300, type='EpochBasedTrainLoop', val_interval=10)
train_data_prefix = 'images/'
train_dataloader = dict(
    batch_size=8,
    collate_fn=dict(type='yolov5_collate'),
    dataset=dict(
        ann_file='annotations/train.json',
        data_prefix=dict(img='images/'),
        data_root='data/asdr6-3-1000oa-split8020/',
        filter_cfg=dict(filter_empty_gt=False, min_size=32),
        metainfo=dict(
            classes=(
                '11522_tx_dyn1',
                '11522_tx_ynyn0d1',
                '115_1way_ds_w_motor',
                '115_3ways_ds_w_motor',
                '115_breaker',
                '115_buffer',
                '115_cvt_1p',
                '115_cvt_3p',
                '115_ds',
                '115_gs',
                '115_gs_w_motor',
                '115_la',
                '115_vt_1p',
                '115_vt_3p',
                '22_breaker',
                '22_cap_bank',
                '22_ds',
                '22_ds_la_out',
                '22_gs',
                '22_ll',
                '22_vt_3p',
                'BCU',
                'DIM',
                'DPM',
                'LL',
                'MU',
                'NGR_future',
                'Q',
                'remote_io_module',
                'ss_man_mode',
                'tele_protection',
                'terminator_double',
                'terminator_single',
                'terminator_splicing_kits',
                'terminator_w_future',
                'v_m',
                'v_m_digital',
            ),
            palette=[
                (
                    0,
                    0,
                    0,
                ),
                (
                    66,
                    0,
                    75,
                ),
                (
                    120,
                    0,
                    137,
                ),
                (
                    130,
                    0,
                    147,
                ),
                (
                    105,
                    0,
                    156,
                ),
                (
                    30,
                    0,
                    166,
                ),
                (
                    0,
                    0,
                    187,
                ),
                (
                    0,
                    0,
                    215,
                ),
                (
                    0,
                    52,
                    221,
                ),
                (
                    0,
                    119,
                    221,
                ),
                (
                    0,
                    137,
                    221,
                ),
                (
                    0,
                    154,
                    215,
                ),
                (
                    0,
                    164,
                    187,
                ),
                (
                    0,
                    170,
                    162,
                ),
                (
                    0,
                    170,
                    143,
                ),
                (
                    0,
                    164,
                    90,
                ),
                (
                    0,
                    154,
                    15,
                ),
                (
                    0,
                    168,
                    0,
                ),
                (
                    0,
                    186,
                    0,
                ),
                (
                    0,
                    205,
                    0,
                ),
                (
                    0,
                    224,
                    0,
                ),
                (
                    0,
                    243,
                    0,
                ),
                (
                    41,
                    255,
                    0,
                ),
                (
                    145,
                    255,
                    0,
                ),
                (
                    203,
                    249,
                    0,
                ),
                (
                    232,
                    239,
                    0,
                ),
                (
                    245,
                    222,
                    0,
                ),
                (
                    255,
                    204,
                    0,
                ),
                (
                    255,
                    175,
                    0,
                ),
                (
                    255,
                    136,
                    0,
                ),
                (
                    255,
                    51,
                    0,
                ),
                (
                    247,
                    0,
                    0,
                ),
                (
                    228,
                    0,
                    0,
                ),
                (
                    215,
                    0,
                    0,
                ),
                (
                    205,
                    0,
                    0,
                ),
                (
                    204,
                    90,
                    90,
                ),
                (
                    204,
                    204,
                    204,
                ),
            ]),
        pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(
                img_scale=(
                    1280,
                    1280,
                ),
                pad_val=114.0,
                pre_transform=[
                    dict(backend_args=None, type='LoadImageFromFile'),
                    dict(type='LoadAnnotations', with_bbox=True),
                ],
                type='Mosaic'),
            dict(
                border=(
                    -640,
                    -640,
                ),
                border_val=(
                    114,
                    114,
                    114,
                ),
                max_rotate_degree=0.0,
                max_shear_degree=0.0,
                scaling_ratio_range=(
                    0.5,
                    1.5,
                ),
                type='YOLOv5RandomAffine'),
            dict(
                bbox_params=dict(
                    format='pascal_voc',
                    label_fields=[
                        'gt_bboxes_labels',
                        'gt_ignore_flags',
                    ],
                    type='BboxParams'),
                keymap=dict(gt_bboxes='bboxes', img='image'),
                transforms=[
                    dict(p=0.01, type='Blur'),
                    dict(p=0.01, type='MedianBlur'),
                    dict(p=0.01, type='ToGray'),
                    dict(p=0.01, type='CLAHE'),
                ],
                type='mmdet.Albu'),
            dict(type='YOLOv5HSVRandomAug'),
            dict(prob=0.5, type='mmdet.RandomFlip'),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'flip',
                    'flip_direction',
                ),
                type='mmdet.PackDetInputs'),
        ],
        type='YOLOv5CocoDataset'),
    num_workers=4,
    persistent_workers=True,
    pin_memory=True,
    sampler=dict(shuffle=True, type='DefaultSampler'))
train_num_workers = 4
train_pipeline = [
    dict(backend_args=None, type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(
        img_scale=(
            1280,
            1280,
        ),
        pad_val=114.0,
        pre_transform=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True),
        ],
        type='Mosaic'),
    dict(
        border=(
            -640,
            -640,
        ),
        border_val=(
            114,
            114,
            114,
        ),
        max_rotate_degree=0.0,
        max_shear_degree=0.0,
        scaling_ratio_range=(
            0.5,
            1.5,
        ),
        type='YOLOv5RandomAffine'),
    dict(
        bbox_params=dict(
            format='pascal_voc',
            label_fields=[
                'gt_bboxes_labels',
                'gt_ignore_flags',
            ],
            type='BboxParams'),
        keymap=dict(gt_bboxes='bboxes', img='image'),
        transforms=[
            dict(p=0.01, type='Blur'),
            dict(p=0.01, type='MedianBlur'),
            dict(p=0.01, type='ToGray'),
            dict(p=0.01, type='CLAHE'),
        ],
        type='mmdet.Albu'),
    dict(type='YOLOv5HSVRandomAug'),
    dict(prob=0.5, type='mmdet.RandomFlip'),
    dict(
        meta_keys=(
            'img_id',
            'img_path',
            'ori_shape',
            'img_shape',
            'flip',
            'flip_direction',
        ),
        type='mmdet.PackDetInputs'),
]
tta_img_scales = [
    (
        1280,
        1280,
    ),
    (
        1024,
        1024,
    ),
    (
        1536,
        1536,
    ),
]
tta_model = dict(
    tta_cfg=dict(max_per_img=300, nms=dict(iou_threshold=0.65, type='nms')),
    type='mmdet.DetTTAModel')
tta_pipeline = [
    dict(backend_args=None, type='LoadImageFromFile'),
    dict(
        transforms=[
            [
                dict(
                    transforms=[
                        dict(
                            scale=(
                                1280,
                                1280,
                            ), type='YOLOv5KeepRatioResize'),
                        dict(
                            allow_scale_up=False,
                            pad_val=dict(img=114),
                            scale=(
                                1280,
                                1280,
                            ),
                            type='LetterResize'),
                    ],
                    type='Compose'),
                dict(
                    transforms=[
                        dict(
                            scale=(
                                1024,
                                1024,
                            ), type='YOLOv5KeepRatioResize'),
                        dict(
                            allow_scale_up=False,
                            pad_val=dict(img=114),
                            scale=(
                                1024,
                                1024,
                            ),
                            type='LetterResize'),
                    ],
                    type='Compose'),
                dict(
                    transforms=[
                        dict(
                            scale=(
                                1536,
                                1536,
                            ), type='YOLOv5KeepRatioResize'),
                        dict(
                            allow_scale_up=False,
                            pad_val=dict(img=114),
                            scale=(
                                1536,
                                1536,
                            ),
                            type='LetterResize'),
                    ],
                    type='Compose'),
            ],
            [
                dict(prob=1.0, type='mmdet.RandomFlip'),
                dict(prob=0.0, type='mmdet.RandomFlip'),
            ],
            [
                dict(type='mmdet.LoadAnnotations', with_bbox=True),
            ],
            [
                dict(
                    meta_keys=(
                        'img_id',
                        'img_path',
                        'ori_shape',
                        'img_shape',
                        'scale_factor',
                        'pad_param',
                        'flip',
                        'flip_direction',
                    ),
                    type='mmdet.PackDetInputs'),
            ],
        ],
        type='TestTimeAug'),
]
val_ann_file = 'annotations/val.json'
val_batch_size_per_gpu = 1
val_cfg = dict(type='ValLoop')
val_data_prefix = 'images/'
val_dataloader = dict(
    batch_size=1,
    dataset=dict(
        ann_file='annotations/val.json',
        batch_shapes_cfg=dict(
            batch_size=1,
            extra_pad_ratio=0.5,
            img_size=1280,
            size_divisor=64,
            type='BatchShapePolicy'),
        data_prefix=dict(img='images/'),
        data_root='data/asdr6-3-1000oa-split8020/',
        metainfo=dict(
            classes=(
                '11522_tx_dyn1',
                '11522_tx_ynyn0d1',
                '115_1way_ds_w_motor',
                '115_3ways_ds_w_motor',
                '115_breaker',
                '115_buffer',
                '115_cvt_1p',
                '115_cvt_3p',
                '115_ds',
                '115_gs',
                '115_gs_w_motor',
                '115_la',
                '115_vt_1p',
                '115_vt_3p',
                '22_breaker',
                '22_cap_bank',
                '22_ds',
                '22_ds_la_out',
                '22_gs',
                '22_ll',
                '22_vt_3p',
                'BCU',
                'DIM',
                'DPM',
                'LL',
                'MU',
                'NGR_future',
                'Q',
                'remote_io_module',
                'ss_man_mode',
                'tele_protection',
                'terminator_double',
                'terminator_single',
                'terminator_splicing_kits',
                'terminator_w_future',
                'v_m',
                'v_m_digital',
            ),
            palette=[
                (
                    0,
                    0,
                    0,
                ),
                (
                    66,
                    0,
                    75,
                ),
                (
                    120,
                    0,
                    137,
                ),
                (
                    130,
                    0,
                    147,
                ),
                (
                    105,
                    0,
                    156,
                ),
                (
                    30,
                    0,
                    166,
                ),
                (
                    0,
                    0,
                    187,
                ),
                (
                    0,
                    0,
                    215,
                ),
                (
                    0,
                    52,
                    221,
                ),
                (
                    0,
                    119,
                    221,
                ),
                (
                    0,
                    137,
                    221,
                ),
                (
                    0,
                    154,
                    215,
                ),
                (
                    0,
                    164,
                    187,
                ),
                (
                    0,
                    170,
                    162,
                ),
                (
                    0,
                    170,
                    143,
                ),
                (
                    0,
                    164,
                    90,
                ),
                (
                    0,
                    154,
                    15,
                ),
                (
                    0,
                    168,
                    0,
                ),
                (
                    0,
                    186,
                    0,
                ),
                (
                    0,
                    205,
                    0,
                ),
                (
                    0,
                    224,
                    0,
                ),
                (
                    0,
                    243,
                    0,
                ),
                (
                    41,
                    255,
                    0,
                ),
                (
                    145,
                    255,
                    0,
                ),
                (
                    203,
                    249,
                    0,
                ),
                (
                    232,
                    239,
                    0,
                ),
                (
                    245,
                    222,
                    0,
                ),
                (
                    255,
                    204,
                    0,
                ),
                (
                    255,
                    175,
                    0,
                ),
                (
                    255,
                    136,
                    0,
                ),
                (
                    255,
                    51,
                    0,
                ),
                (
                    247,
                    0,
                    0,
                ),
                (
                    228,
                    0,
                    0,
                ),
                (
                    215,
                    0,
                    0,
                ),
                (
                    205,
                    0,
                    0,
                ),
                (
                    204,
                    90,
                    90,
                ),
                (
                    204,
                    204,
                    204,
                ),
            ]),
        pipeline=[
            dict(backend_args=None, type='LoadImageFromFile'),
            dict(scale=(
                1280,
                1280,
            ), type='YOLOv5KeepRatioResize'),
            dict(
                allow_scale_up=False,
                pad_val=dict(img=114),
                scale=(
                    1280,
                    1280,
                ),
                type='LetterResize'),
            dict(type='mmdet.LoadAnnotations', with_bbox=True),
            dict(
                meta_keys=(
                    'img_id',
                    'img_path',
                    'ori_shape',
                    'img_shape',
                    'scale_factor',
                    'pad_param',
                ),
                type='mmdet.PackDetInputs'),
        ],
        test_mode=True,
        type='YOLOv5CocoDataset'),
    drop_last=False,
    num_workers=2,
    persistent_workers=True,
    pin_memory=True,
    sampler=dict(shuffle=False, type='DefaultSampler'))
val_evaluator = dict(
    ann_file='data/asdr6-3-1000oa-split8020/annotations/val.json',
    metric='bbox',
    proposal_nums=(
        100,
        1,
        10,
    ),
    type='mmdet.CocoMetric')
val_num_workers = 2
vis_backend = [
    dict(type='LocalVisBackend'),
]
vis_backends = [
    dict(type='LocalVisBackend'),
]
visualizer = dict(
    name='visualizer',
    type='mmdet.DetLocalVisualizer',
    vis_backends=[
        dict(type='LocalVisBackend'),
    ])
weight_decay = 0.0005
widen_factor = 0.5
